#EXTM3U
#EXTINF:0, En total
http://www.m3u.cl/lista/total.m3u
#EXTINF:0, ***Paises***

#EXTINF:0, Paraguay
http://www.m3u.cl/lista/PY.m3u
#EXTINF:0, Argentina
http://www.m3u.cl/lista/AR.m3u
#EXTINF:0, Bolivia
http://www.m3u.cl/lista/BO.m3u
#EXTINF:0, Chile
http://www.m3u.cl/lista/CL.m3u
#EXTINF:0, Colombia
http://www.m3u.cl/lista/CO.m3u
#EXTINF:0, Ecuador
http://www.m3u.cl/lista/EC.m3u
#EXTINF:0, España
http://www.m3u.cl/lista/ES.m3u
#EXTINF:0, Mexico
http://www.m3u.cl/lista/MX.m3u
#EXTINF:0, Peru
http://www.m3u.cl/lista/PE.m3u
#EXTINF:0, Republica Dominicana
http://www.m3u.cl/lista/DO.m3u
#EXTINF:0, Venezuela
http://www.m3u.cl/lista/VE.m3u
#EXTINF:0, ***Categorias***

#EXTINF:0, Musica
http://www.m3u.cl/lista/musica.m3u
#EXTINF:0, Religiosos
http://www.m3u.cl/lista/religiosos.m3u
#EXTINF:0, Adultos
http://www.m3u.cl/playlist/XXX.m3u
